project:
  type: website
  output-dir: ../docs

website:
  title: "RGS-IBG GIScience Research Group"
  site-url: https://giscience-rgs.github.io
  description: "GIScience Research Group (GIScRG) at the Royal Geographical Society with IBG"
  favicon: images/cropped-rgs_favicon.png
  page-footer: "[RGS-IBG GIScience Research Group](https://giscience-rgs.github.io) | [RSS](https://giscience-rgs.github.io/news.xml) | [Code of conduct](https://www.rgs.org/about/the-society/governance/code-of-conduct/) | [GDPR privacy notice](https://www.rgs.org/privacy-notice/)"
  navbar:
    right:
      - href: index.qmd
        text: "About"
      - href: people.qmd
        text: "People"
      - href: news.qmd
        text: "News"
      - text: "Events"
        menu:
        - href: giscience-webinar-series.qmd
          text: "GIScience Webinar Series"
        - href: conferences.qmd
          text: "Conferences"
        - href: sessions-rgs-aic-2025.qmd
          text: "RGS-IBG AIC 2025"
        - href: call-for-session-sponsorship-2026.qmd
          text: "RGS-IBG AIC 2026 Sponsorship"
        - href: sessions-rgs-aic-2026.qmd
          text: "RGS-IBG AIC 2026 CfPs"
      - text: "Prizes"
        menu:
        - href: dissertation-prizes.qmd
          text: "Dissertation prizes"
      - icon: rss-fill
        href: news.xml
      - icon: linkedin
        href: https://www.linkedin.com/groups/12939516/
      - icon: github
        href: https://github.com/giscience-rgs
      - icon: youtube
        href: https://www.youtube.com/@rgs-ibggiscienceresearchgr5599

format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom.scss]
    css: styles.css
    toc: true



